export const mtf = [
  { name: 'C.E. INFO SYSTEMS LIMITED', symbol: 'MAPMYINDIA', percent: 65.0 },
  { name: 'BIRLASOFT LIMITED', symbol: 'BSOFT', percent: 70.0 },
  { name: 'GLENMARK PHARMACEUTICALS', symbol: 'GLENMARK', percent: 70.0 },
  { name: 'SKF INDIA LTD', symbol: 'SKFINDIA', percent: 60.0 },
  { name: 'NOCIL LIMITED', symbol: 'NOCIL', percent: 60.0 },
  { name: 'MARICO LIMITED', symbol: 'MARICO', percent: 75.0 },
  { name: 'ASTER DM HEALTHCARE LTD.', symbol: 'ASTERDM', percent: 60.0 },
  { name: 'SOBHA LIMITED', symbol: 'SOBHA', percent: 60.0 },
  { name: 'TUBE INVEST OF INDIA LTD', symbol: 'TIINDIA', percent: 60.0 },
  { name: 'GMM PFAUDLER LIMITED', symbol: 'GMMPFAUDLR', percent: 60.0 },
  { name: 'NTPC LTD', symbol: 'NTPC', percent: 75.0 },
  { name: 'INDIAN OIL CORP LTD', symbol: 'IOC', percent: 75.0 },
  { name: 'SOLAR INDUSTRIES (I) LTD', symbol: 'SOLARINDS', percent: 60.0 },
  { name: 'CAMPUS ACTIVEWEAR LIMITED', symbol: 'CAMPUS', percent: 65.0 },
  { name: 'TIMKEN INDIA LTD.', symbol: 'TIMKEN', percent: 60.0 },
  { name: 'ASTRAL LIMITED', symbol: 'ASTRAL', percent: 70.0 },
  { name: 'CYIENT LIMITED', symbol: 'CYIENT', percent: 60.0 },
  { name: 'GUJ NAR VAL FER \u0026 CHEM L', symbol: 'GNFC', percent: 65.0 },
  { name: 'MARUTI SUZUKI INDIA LTD.', symbol: 'MARUTI', percent: 75.0 },
  { name: 'VOLTAMP TRANSFORMERS LTD', symbol: 'VOLTAMP', percent: 60.0 },
  { name: 'NUVOCO VISTAS CORP LTD', symbol: 'NUVOCO', percent: 60.0 },
  { name: 'SONA BLW PRECISION FRGS L', symbol: 'SONACOMS', percent: 60.0 },
  { name: 'THE TINPLATE CO. (I) LTD', symbol: 'TINPLATE', percent: 60.0 },
  { name: 'COMPUTER AGE MNGT SER LTD', symbol: 'CAMS', percent: 65.0 },
  { name: 'VOLTAS LTD', symbol: 'VOLTAS', percent: 75.0 },
  { name: 'FSN E COMMERCE VENTURES', symbol: 'NYKAA', percent: 60.0 },
  { name: 'ATUL LTD', symbol: 'ATUL', percent: 70.0 },
  { name: 'CANARA BANK', symbol: 'CANBK', percent: 65.0 },
  { name: 'GODREJ AGROVET LIMITED', symbol: 'GODREJAGRO', percent: 60.0 },
  { name: 'DABUR INDIA LTD', symbol: 'DABUR', percent: 80.0 },
  { name: 'SONATA SOFTWARE LTD', symbol: 'SONATSOFTW', percent: 60.0 },
  { name: 'TITAN COMPANY LIMITED', symbol: 'TITAN', percent: 75.0 },
  { name: 'MASTEK LTD', symbol: 'MASTEK', percent: 60.0 },
  { name: 'AU SMALL FINANCE BANK LTD', symbol: 'AUBANK', percent: 70.0 },
  { name: 'VRL LOGISTICS LIMITED', symbol: 'VRLLOG', percent: 60.0 },
  { name: 'CAN FIN HOMES LTD', symbol: 'CANFINHOME', percent: 65.0 },
  { name: 'OBEROI REALTY LIMITED', symbol: 'OBEROIRLTY', percent: 70.0 },
  { name: 'DALMIA BHARAT LIMITED', symbol: 'DALBHARAT', percent: 70.0 },
  { name: 'SRF LTD', symbol: 'SRF', percent: 70.0 },
  { name: 'AUROBINDO PHARMA LTD', symbol: 'AUROPHARMA', percent: 70.0 },
  { name: 'TORRENT PHARMACEUTICALS L', symbol: 'TORNTPHARM', percent: 75.0 },
  { name: 'ORACLE FIN SERV SOFT LTD.', symbol: 'OFSS', percent: 70.0 },
  { name: 'VARDHMAN TEXTILES LIMITED', symbol: 'VTL', percent: 60.0 },
  { name: 'GODREJ CONSUMER PRODUCTS', symbol: 'GODREJCP', percent: 75.0 },
  { name: 'CARBORUNDUM UNIVERSAL LTD', symbol: 'CARBORUNIV', percent: 60.0 },
  { name: 'INDIAN RAIL TOUR CORP LTD', symbol: 'IRCTC', percent: 65.0 },
  { name: 'OIL INDIA LTD', symbol: 'OIL', percent: 60.0 },
  { name: 'UNITED SPIRITS LIMITED', symbol: 'MCDOWELL-N', percent: 70.0 },
  { name: 'VA TECH WABAG LTD', symbol: 'WABAG', percent: 60.0 },
  { name: 'TORRENT POWER LTD', symbol: 'TORNTPOWER', percent: 65.0 },
  { name: 'SHREE CEMENT LIMITED', symbol: 'SHREECEM', percent: 75.0 },
  { name: 'CARE RATINGS LIMITED', symbol: 'CARERATING', percent: 60.0 },
  { name: 'GODREJ INDUSTRIES LTD', symbol: 'GODREJIND', percent: 60.0 },
  { name: 'INDIAN RAILWAY FIN CORP L', symbol: 'IRFC', percent: 60.0 },
  { name: 'WELSPUN CORP LIMITED', symbol: 'WELCORP', percent: 60.0 },
  { name: 'TRENT LTD', symbol: 'TRENT', percent: 70.0 },
  { name: 'MAHINDRA \u0026 MAHINDRA LTD', symbol: 'M\u0026M', percent: 75.0 },
  { name: 'DCB BANK LIMITED', symbol: 'DCBBANK', percent: 60.0 },
  { name: 'OIL AND NATURAL GAS CORP.', symbol: 'ONGC', percent: 70.0 },
  { name: 'SHRIRAM FINANCE LIMITED', symbol: 'SHRIRAMFIN', percent: 70.0 },
  { name: 'CASTROL INDIA LIMITED', symbol: 'CASTROLIND', percent: 60.0 },
  { name: 'ICICI SECURITIES LIMITED', symbol: 'ISEC', percent: 65.0 },
  { name: 'WHIRLPOOL OF INDIA LTD', symbol: 'WHIRLPOOL', percent: 70.0 },
  { name: 'M\u0026M FIN. SERVICES LTD', symbol: 'M\u0026MFIN', percent: 70.0 },
  { name: 'TTK PRESTIGE LTD', symbol: 'TTKPRESTIG', percent: 60.0 },
  { name: 'CCL PRODUCTS (I) LTD', symbol: 'CCL', percent: 60.0 },
  { name: 'DCM SHRIRAM LIMITED', symbol: 'DCMSHRIRAM', percent: 60.0 },
  { name: 'ITC LTD', symbol: 'ITC', percent: 75.0 },
  { name: 'ORIENT ELECTRIC LIMITED', symbol: 'ORIENTELEC', percent: 60.0 },
  { name: 'WIPRO LTD', symbol: 'WIPRO', percent: 75.0 },
  { name: 'THE GE SHPG.LTD', symbol: 'GESHIP', percent: 60.0 },
  { name: 'TVS MOTOR COMPANY  LTD', symbol: 'TVSMOTOR', percent: 75.0 },
  { name: 'BANK OF MAHARASHTRA', symbol: 'MAHABANK', percent: 60.0 },
  {
    name: 'DEEPAK FERTILIZERS \u0026 PETR',
    symbol: 'DEEPAKFERT',
    percent: 60.0,
  },
  { name: 'PAGE INDUSTRIES LTD', symbol: 'PAGEIND', percent: 75.0 },
  { name: 'GHCL LIMITED', symbol: 'GHCL', percent: 60.0 },
  { name: 'CENTURY PLYBOARDS (I) LTD', symbol: 'CENTURYPLY', percent: 60.0 },
  { name: 'INTERGLOBE AVIATION LTD', symbol: 'INDIGO', percent: 70.0 },
  { name: 'MAHINDRA LIFESPACE DEVLTD', symbol: 'MAHLIFE', percent: 60.0 },
  { name: 'UNITED BREWERIES LTD', symbol: 'UBL', percent: 75.0 },
  { name: 'ZEE ENTERTAINMENT ENT LTD', symbol: 'ZEEL', percent: 60.0 },
  { name: 'DEEPAK NITRITE LTD', symbol: 'DEEPAKNTR', percent: 65.0 },
  { name: 'CENTURY TEXTILES LTD', symbol: 'CENTURYTEX', percent: 60.0 },
  { name: 'INDIGO PAINTS LIMITED', symbol: 'INDIGOPNTS', percent: 65.0 },
  { name: 'PARAS DEF AND SPCE TECH L', symbol: 'PARAS', percent: 60.0 },
  { name: 'GENERAL INS CORP OF INDIA', symbol: 'GICRE', percent: 60.0 },
  { name: 'SUN TV NETWORK LIMITED', symbol: 'SUNTV', percent: 65.0 },
  { name: 'MAHARASHTRA SEAMLESS LTD', symbol: 'MAHSEAMLES', percent: 60.0 },
  { name: 'UJJIVAN FIN. SERVC. LTD.', symbol: 'UJJIVAN', percent: 60.0 },
  { name: 'DELTA CORP LIMITED', symbol: 'DELTACORP', percent: 60.0 },
  { name: 'ZF COM VE CTR SYS IND LTD', symbol: 'ZFCVINDIA', percent: 60.0 },
  { name: 'INDUSIND BANK LIMITED', symbol: 'INDUSINDBK', percent: 70.0 },
  { name: 'SUPREME INDUSTRIES LTD', symbol: 'SUPREMEIND', percent: 60.0 },
  { name: 'MANAPPURAM FINANCE LTD', symbol: 'MANAPPURAM', percent: 65.0 },
  { name: 'CESC LTD', symbol: 'CESC', percent: 65.0 },
  { name: 'NESCO LTD.', symbol: 'NESCO', percent: 60.0 },
  { name: 'INDUS TOWERS LIMITED', symbol: 'INDUSTOWER', percent: 70.0 },
  { name: 'DEVYANI INTERNATIONAL LTD', symbol: 'DEVYANI', percent: 60.0 },
  { name: 'GLAXOSMITHKLINE PHARMA LT', symbol: 'GLAXO', percent: 65.0 },
  { name: 'ZYDUS LIFESCIENCES LTD', symbol: 'ZYDUSLIFE', percent: 75.0 },
  { name: 'SUPRIYA LIFESCIENCE LTD', symbol: 'SUPRIYA', percent: 60.0 },
  { name: 'CAPRI GLOBAL CAPITAL LTD', symbol: 'CGCL', percent: 60.0 },
  { name: 'ZYDUS WELLNESS LIMITED', symbol: 'ZYDUSWELL', percent: 60.0 },
  { name: 'DIVI S LABORATORIES LTD', symbol: 'DIVISLAB', percent: 75.0 },
  { name: 'INFOSYS LIMITED', symbol: 'INFY', percent: 75.0 },
  { name: 'TATA CONSULTANCY SERV LT', symbol: 'TCS', percent: 75.0 },
  { name: 'SUVEN PHARMACEUTICALS LTD', symbol: 'SUVENPHAR', percent: 60.0 },
  { name: 'MEGHMANI ORGANICS LIMITED', symbol: 'MOL', percent: 60.0 },
  { name: 'CHALET HOTELS LIMITED', symbol: 'CHALET', percent: 60.0 },
  { name: 'GRINDWELL NORTON LIMITED', symbol: 'GRINDWELL', percent: 60.0 },
  { name: 'TEAMLEASE SERVICES LTD.', symbol: 'TEAMLEASE', percent: 60.0 },
  { name: 'CHAMBAL FERTILIZERS LTD', symbol: 'CHAMBLFERT', percent: 65.0 },
  { name: 'SAMVRDHNA MTHRSN INTL LTD', symbol: 'MOTHERSON', percent: 70.0 },
  { name: 'NARAYANA HRUDAYALAYA LTD.', symbol: 'NH', percent: 60.0 },
  { name: 'DLF LIMITED', symbol: 'DLF', percent: 70.0 },
  { name: 'SYNGENE INTERNATIONAL LTD', symbol: 'SYNGENE', percent: 70.0 },
  { name: 'VARUN BEVERAGES LIMITED', symbol: 'VBL', percent: 60.0 },
  { name: 'INTELLECT DESIGN ARENA', symbol: 'INTELLECT', percent: 60.0 },
  { name: 'GUJ STATE FERT \u0026 CHEM LTD', symbol: 'GSFC', percent: 60.0 },
  { name: 'MOTILAL OSWAL FIN LTD', symbol: 'MOTILALOFS', percent: 60.0 },
  { name: 'TECH MAHINDRA LIMITED', symbol: 'TECHM', percent: 75.0 },
  { name: 'BIRLA CORPORATION LTD', symbol: 'BIRLACORPN', percent: 60.0 },
  { name: 'AVENUE SUPERMARTS LIMITED', symbol: 'DMART', percent: 65.0 },
  { name: 'VEDANTA LIMITED', symbol: 'VEDL', percent: 60.0 },
  { name: 'TANLA PLATFORMS LIMITED', symbol: 'TANLA', percent: 60.0 },
  { name: 'NIP IND ETF NIFTY BEES', symbol: 'NIFTYBEES', percent: 75.0 },
  { name: 'MPHASIS LIMITED', symbol: 'MPHASIS', percent: 70.0 },
  { name: 'BLUE DART EXPRESS LTD', symbol: 'BLUEDART', percent: 60.0 },
  { name: 'THERMAX LTD', symbol: 'THERMAX', percent: 60.0 },
  { name: 'COFORGE LIMITED', symbol: 'COFORGE', percent: 70.0 },
  { name: 'JKUMAR INFR.LTD.', symbol: 'JKIL', percent: 60.0 },
  { name: 'STERLITE TECHNOLOGIES LTD', symbol: 'STLTECH', percent: 60.0 },
  { name: 'TATA CHEMICALS LTD', symbol: 'TATACHEM', percent: 65.0 },
  { name: 'BLUE STAR LIMITED', symbol: 'BLUESTARCO', percent: 65.0 },
  { name: 'JK LAKSHMI CEMENT LTD', symbol: 'JKLAKSHMI', percent: 60.0 },
  { name: 'GUJARAT STATE PETRO LTD', symbol: 'GSPL', percent: 65.0 },
  { name: 'V-GUARD IND LTD.', symbol: 'VGUARD', percent: 60.0 },
  { name: 'STOVE KRAFT LIMITED', symbol: 'STOVEKRAFT', percent: 60.0 },
  { name: 'AVANTI FEEDS LIMITED', symbol: 'AVANTIFEED', percent: 60.0 },
  { name: 'JK PAPER LIMITED', symbol: 'JKPAPER', percent: 60.0 },
  { name: 'GUJARAT GAS LIMITED', symbol: 'GUJGASLTD', percent: 65.0 },
  { name: 'SUDARSHAN CHEMICAL INDS L', symbol: 'SUDARSCHEM', percent: 60.0 },
  { name: 'VINATI ORGANICS LTD', symbol: 'VINATIORGA', percent: 60.0 },
  { name: 'TATA COFFEE LIMITED', symbol: 'TATACOFFEE', percent: 60.0 },
  { name: 'APOLLO HOSPITALS ENTER. L', symbol: 'APOLLOHOSP', percent: 70.0 },
  { name: 'BOSCH LIMITED', symbol: 'BOSCHLTD', percent: 70.0 },
  { name: 'BALRAMPUR CHINI MILLS LTD', symbol: 'BALRAMCHIN', percent: 65.0 },
  { name: 'HINDUSTAN AERONAUTICS LTD', symbol: 'HAL', percent: 65.0 },
  { name: 'JM FINANCIAL LIMITED', symbol: 'JMFINANCIL', percent: 60.0 },
  { name: 'SUMITOMO CHEM INDIA LTD', symbol: 'SUMICHEM', percent: 60.0 },
  { name: 'BHARAT PETROLEUM CORP  LT', symbol: 'BPCL', percent: 75.0 },
  { name: 'APOLLO TYRES LTD', symbol: 'APOLLOTYRE', percent: 70.0 },
  { name: 'MRF LTD', symbol: 'MRF', percent: 75.0 },
  { name: 'COLGATE PALMOLIVE LTD.', symbol: 'COLPAL', percent: 75.0 },
  { name: 'HAPPIEST MINDS TECHNO LTD', symbol: 'HAPPSTMNDS', percent: 60.0 },
  { name: 'JSW STEEL LIMITED', symbol: 'JSWSTEEL', percent: 70.0 },
  { name: 'BRIGADE ENTER. LTD', symbol: 'BRIGADE', percent: 60.0 },
  { name: 'APTUS VALUE HSG FIN I LTD', symbol: 'APTUS', percent: 60.0 },
  { name: 'NIIT LIMITED', symbol: 'NIITLTD', percent: 60.0 },
  { name: 'CONTAINER CORP OF IND LTD', symbol: 'CONCOR', percent: 70.0 },
  { name: 'SUNDARAM FINANCE LTD', symbol: 'SUNDARMFIN', percent: 60.0 },
  { name: 'UJJIVAN SMALL FINANC BANK', symbol: 'UJJIVANSFB', percent: 60.0 },
  { name: 'JUBILANT FOODWORKS LTD', symbol: 'JUBLFOOD', percent: 70.0 },
  { name: 'BRITANNIA INDUSTRIES LTD', symbol: 'BRITANNIA', percent: 75.0 },
  { name: 'GODREJ PROPERTIES LTD', symbol: 'GODREJPROP', percent: 70.0 },
  { name: 'COROMANDEL INTERNTL. LTD', symbol: 'COROMANDEL', percent: 75.0 },
  { name: 'ASAHI INDIA GLASS LIMITED', symbol: 'ASAHIINDIA', percent: 60.0 },
  { name: 'CPSE ETF', symbol: 'CPSEETF', percent: 70.0 },
  { name: 'JUBILANT INGREVIA LIMITED', symbol: 'JUBLINGREA', percent: 60.0 },
  { name: 'NLC INDIA LIMITED', symbol: 'NLCINDIA', percent: 60.0 },
  { name: 'BHARAT DYNAMICS LIMITED', symbol: 'BDL', percent: 60.0 },
  { name: 'SUN PHARMACEUTICAL IND L', symbol: 'SUNPHARMA', percent: 75.0 },
  { name: 'MTAR TECHNOLOGIES LIMITED', symbol: 'MTARTECH', percent: 60.0 },
  { name: 'GOODYEAR INDIA LIMITED', symbol: 'GOODYEAR', percent: 60.0 },
  { name: 'AIA ENGINEERING LIMITED', symbol: 'AIAENG', percent: 65.0 },
  { name: 'ASHOKA BUILDCON LTD', symbol: 'ASHOKA', percent: 60.0 },
  { name: 'NIP IND ETF JUNIOR BEES', symbol: 'JUNIORBEES', percent: 60.0 },
  { name: 'SUNTECK REALTY LIMITED', symbol: 'SUNTECK', percent: 60.0 },
  { name: 'BHARAT ELECTRONICS LTD', symbol: 'BEL', percent: 70.0 },
  { name: 'MUTHOOT FINANCE LIMITED', symbol: 'MUTHOOTFIN', percent: 70.0 },
  { name: 'GUJARAT PIPAVAV PORT LTD', symbol: 'GPPL', percent: 60.0 },
  { name: 'ASHOK LEYLAND LTD', symbol: 'ASHOKLEY', percent: 70.0 },
  { name: 'CRISIL LTD', symbol: 'CRISIL', percent: 60.0 },
  { name: 'BEML LIMITED', symbol: 'BEML', percent: 60.0 },
  { name: 'NATCO PHARMA LTD.', symbol: 'NATCOPHARM', percent: 60.0 },
  { name: 'GRANULES INDIA LIMITED', symbol: 'GRANULES', percent: 65.0 },
  { name: 'ULTRATECH CEMENT LIMITED', symbol: 'ULTRACEMCO', percent: 75.0 },
  { name: 'CROMPT GREA CON ELEC LTD', symbol: 'CROMPTON', percent: 75.0 },
  { name: 'ASIAN PAINTS LIMITED', symbol: 'ASIANPAINT', percent: 75.0 },
  { name: 'SAPPHIRE FOODS INDIA LTD', symbol: 'SAPPHIRE', percent: 60.0 },
  { name: 'JAMNA AUTO IND LTD', symbol: 'JAMNAAUTO', percent: 60.0 },
  { name: 'NATIONAL ALUMINIUM CO LTD', symbol: 'NATIONALUM', percent: 65.0 },
  { name: 'MULTI COMMODITY EXCHANGE', symbol: 'MCX', percent: 70.0 },
  { name: 'GRAPHITE INDIA LTD', symbol: 'GRAPHITE', percent: 60.0 },
  { name: 'BERGER PAINTS (I) LTD', symbol: 'BERGEPAINT', percent: 75.0 },
  { name: 'CITY UNION BANK LTD', symbol: 'CUB', percent: 70.0 },
  { name: 'MEDPLUS HEALTH SERV LTD', symbol: 'MEDPLUS', percent: 60.0 },
  { name: 'INFO EDGE (I) LTD', symbol: 'NAUKRI', percent: 70.0 },
  { name: 'AJANTA PHARMA LIMITED', symbol: 'AJANTPHARM', percent: 70.0 },
  { name: 'J B CHEMICALS AND PHARMA', symbol: 'JBCHEPHARM', percent: 60.0 },
  { name: 'UNION BANK OF INDIA', symbol: 'UNIONBANK', percent: 60.0 },
  { name: 'GRASIM INDUSTRIES LTD', symbol: 'GRASIM', percent: 75.0 },
  { name: 'BHARAT FORGE LTD', symbol: 'BHARATFORG', percent: 70.0 },
  { name: 'KRBL LIMITED', symbol: 'KRBL', percent: 60.0 },
  { name: 'SBI CARDS \u0026 PAY SER LTD', symbol: 'SBICARD', percent: 75.0 },
  { name: 'METROPOLIS HEALTHCARE LTD', symbol: 'METROPOLIS', percent: 65.0 },
  { name: 'UNO MINDA LIMITED', symbol: 'UNOMINDA', percent: 60.0 },
  { name: 'BHARTI AIRTEL LIMITED', symbol: 'BHARTIARTL', percent: 75.0 },
  { name: 'GRAUER \u0026 WEIL IND LTD', symbol: 'GRAUWEIL', percent: 60.0 },
  { name: 'TATA COMMUNICATIONS LTD', symbol: 'TATACOMM', percent: 70.0 },
  { name: 'NAVIN FLUORINE INT. LTD', symbol: 'NAVINFLUOR', percent: 70.0 },
  {
    name: 'JINDAL STEEL \u0026 POWER LTD',
    symbol: 'JINDALSTEL',
    percent: 65.0,
  },
  { name: 'CHOLAMANDALAM IN \u0026 FIN CO', symbol: 'CHOLAFIN', percent: 70.0 },
  { name: 'MAX FINANCIAL SERV LTD', symbol: 'MFSL', percent: 60.0 },
  { name: 'KARNATAKA BANK LIMITED', symbol: 'KTKBANK', percent: 60.0 },
  { name: 'BHEL', symbol: 'BHEL', percent: 65.0 },
  { name: 'STATE BANK OF INDIA', symbol: 'SBIN', percent: 75.0 },
  { name: 'UPL LIMITED', symbol: 'UPL', percent: 75.0 },
  { name: 'TATA CONSUMER PRODUCT LTD', symbol: 'TATACONSUM', percent: 75.0 },
  { name: 'JK CEMENT LIMITED', symbol: 'JKCEMENT', percent: 70.0 },
  { name: 'GREENPANEL INDUSTRIES LTD', symbol: 'GREENPANEL', percent: 60.0 },
  { name: 'NBCC (INDIA) LIMITED', symbol: 'NBCC', percent: 60.0 },
  { name: 'MAHANAGAR GAS LTD.', symbol: 'MGL', percent: 70.0 },
  { name: 'SCHAEFFLER INDIA LIMITED', symbol: 'SCHAEFFLER', percent: 60.0 },
  { name: 'BIOCON LIMITED.', symbol: 'BIOCON', percent: 65.0 },
  {
    name: 'L\u0026T FINANCE HOLDINGS LTD',
    symbol: 'L\u0026TFH',
    percent: 65.0,
  },
  { name: 'CIE AUTOMOTIVE INDIA LTD', symbol: 'CIEINDIA', percent: 60.0 },
  { name: 'NCC LIMITED', symbol: 'NCC', percent: 60.0 },
  { name: 'UTI ASSET MNGMT CO LTD', symbol: 'UTIAMC', percent: 60.0 },
  { name: 'HONEYWELL AUTOMATION IND', symbol: 'HONAUT', percent: 70.0 },
  { name: 'TATA ELXSI LIMITED', symbol: 'TATAELXSI', percent: 60.0 },
  { name: 'EXIDE INDUSTRIES LTD', symbol: 'EXIDEIND', percent: 70.0 },
  { name: 'MAHINDRA HOLIDAYS LTD', symbol: 'MHRIL', percent: 60.0 },
  { name: 'SHIPPING CORP OF INDIA LT', symbol: 'SCI', percent: 60.0 },
  { name: 'DR. LAL PATH LABS LTD.', symbol: 'LALPATHLAB', percent: 70.0 },
  { name: 'ENDURANCE TECHNO. LTD.', symbol: 'ENDURANCE', percent: 60.0 },
  { name: 'CIPLA LTD', symbol: 'CIPLA', percent: 75.0 },
  { name: 'MISHRA DHATU NIGAM LTD', symbol: 'MIDHANI', percent: 60.0 },
  { name: 'TATA INVESTMENT CORP LTD', symbol: 'TATAINVEST', percent: 65.0 },
  { name: 'LA OPALA RG LIMITED', symbol: 'LAOPALA', percent: 60.0 },
  { name: 'PRESTIGE ESTATE LTD', symbol: 'PRESTIGE', percent: 60.0 },
  { name: 'ENGINEERS INDIA LTD', symbol: 'ENGINERSIN', percent: 60.0 },
  { name: 'CMS INFO SYSTEMS LIMITED', symbol: 'CMSINFO', percent: 70.0 },
  { name: 'FDC LIMITED', symbol: 'FDC', percent: 60.0 },
  { name: 'MINDA CORPORATION LTD', symbol: 'MINDACORP', percent: 60.0 },
  { name: 'ROLEX RINGS LIMITED', symbol: 'ROLEXRINGS', percent: 60.0 },
  { name: 'LATENT VIEW ANALYTICS LTD', symbol: 'LATENTVIEW', percent: 60.0 },
  { name: 'COAL INDIA LTD', symbol: 'COALINDIA', percent: 70.0 },
  { name: 'ICICI BANK LTD.', symbol: 'ICICIBANK', percent: 75.0 },
  { name: 'FEDERAL BANK LTD', symbol: 'FEDERALBNK', percent: 70.0 },
  { name: 'PRINCE PIPES FITTINGS LTD', symbol: 'PRINCEPIPE', percent: 60.0 },
  { name: 'TATA MOTORS LIMITED', symbol: 'TATAMOTORS', percent: 70.0 },
  { name: 'EQUITAS SMALL FIN BNK LTD', symbol: 'EQUITASBNK', percent: 60.0 },
  { name: 'LAURUS LABS LIMITED', symbol: 'LAURUSLABS', percent: 70.0 },
  { name: 'COCHIN SHIPYARD LIMITED', symbol: 'COCHINSHIP', percent: 60.0 },
  { name: 'ROUTE MOBILE LIMITED', symbol: 'ROUTE', percent: 60.0 },
  { name: 'ICICI LOMBARD GIC LIMITED', symbol: 'ICICIGI', percent: 75.0 },
  { name: 'PNB HOUSING FIN LTD.', symbol: 'PNBHOUSING', percent: 60.0 },
  { name: 'LEMON TREE HOTELS LTD', symbol: 'LEMONTREE', percent: 60.0 },
  { name: 'TATA MOTORS DVR  A  ORD', symbol: 'TATAMTRDVR', percent: 60.0 },
  { name: 'FINOLEX CABLES LTD', symbol: 'FINCABLES', percent: 60.0 },
  { name: 'SHILPA MEDICARE LTD', symbol: 'SHILPAMED', percent: 60.0 },
  { name: 'ICICI PRU LIFE INS CO LTD', symbol: 'ICICIPRULI', percent: 75.0 },
  { name: 'ESCORTS KUBOTA LIMITED', symbol: 'ESCORTS', percent: 65.0 },
  { name: 'NIP IND ETF PSU BANK BEES', symbol: 'PSUBNKBEES', percent: 70.0 },
  { name: 'PB FINTECH LIMITED', symbol: 'POLICYBZR', percent: 60.0 },
  { name: 'DR. REDDY S LABORATORIES', symbol: 'DRREDDY', percent: 75.0 },
  { name: 'TATA POWER CO LTD', symbol: 'TATAPOWER', percent: 70.0 },
  { name: 'SAFARI IND (INDIA) LTD', symbol: 'SAFARI', percent: 65.0 },
  { name: 'FINE ORGANIC IND. LTD.', symbol: 'FINEORG', percent: 60.0 },
  { name: 'SHOPPERS STOP LIMITED', symbol: 'SHOPERSTOP', percent: 60.0 },
  { name: 'PVR INOX LIMITED', symbol: 'PVRINOX', percent: 65.0 },
  { name: 'LIC HOUSING FINANCE LTD', symbol: 'LICHSGFIN', percent: 65.0 },
  { name: 'IDBI BANK LIMITED', symbol: 'IDBI', percent: 60.0 },
  { name: 'POLYCAB INDIA LIMITED', symbol: 'POLYCAB', percent: 65.0 },
  { name: 'ECLERX SERVICES LTD', symbol: 'ECLERX', percent: 60.0 },
  { name: 'TATA STEEL LIMITED', symbol: 'TATASTEEL', percent: 70.0 },
  { name: 'STEEL AUTHORITY OF INDIA', symbol: 'SAIL', percent: 65.0 },
  { name: 'LIFE INSURA CORP OF INDIA', symbol: 'LICI', percent: 70.0 },
  { name: 'RADICO KHAITAN LTD', symbol: 'RADICO', percent: 60.0 },
  { name: 'IDFC LIMITED', symbol: 'IDFC', percent: 65.0 },
  { name: 'AXIS BANK LIMITED', symbol: 'AXISBANK', percent: 75.0 },
  { name: 'EICHER MOTORS LTD', symbol: 'EICHERMOT', percent: 75.0 },
  { name: 'GUJARAT FLUOROCHEM LTD', symbol: 'FLUOROCHEM', percent: 60.0 },
  { name: 'RAJESH EXPORTS LTD', symbol: 'RAJESHEXPO', percent: 60.0 },
  { name: 'LINDE INDIA LIMITED', symbol: 'LINDEINDIA', percent: 60.0 },
  { name: 'REC LIMITED', symbol: 'RECLTD', percent: 75.0 },
  { name: 'RAILTEL CORP OF IND LTD', symbol: 'RAILTEL', percent: 60.0 },
  { name: 'BAJAJ AUTO LIMITED', symbol: 'BAJAJ-AUTO', percent: 75.0 },
  { name: 'IDFC FIRST BANK LIMITED', symbol: 'IDFCFIRSTB', percent: 70.0 },
  { name: 'EID PARRY INDIA LTD', symbol: 'EIDPARRY', percent: 60.0 },
  { name: 'POWER GRID CORP. LTD.', symbol: 'POWERGRID', percent: 75.0 },
  { name: 'RALLIS INDIA LTD', symbol: 'RALLIS', percent: 60.0 },
  { name: 'FORTIS HEALTHCARE LTD', symbol: 'FORTIS', percent: 60.0 },
  { name: 'LARSEN \u0026 TOUBRO LTD.', symbol: 'LT', percent: 75.0 },
  { name: 'INDIAN ENERGY EXC LTD', symbol: 'IEX', percent: 65.0 },
  { name: 'RAIN INDUSTRIES LIMITED', symbol: 'RAIN', percent: 65.0 },
  { name: 'HITACHI ENERGY INDIA LTD', symbol: 'POWERINDIA', percent: 60.0 },
  { name: 'FIRSTSOURCE SOLU. LTD.', symbol: 'FSL', percent: 65.0 },
  { name: 'THE RAMCO CEMENTS LIMITED', symbol: 'RAMCOCEM', percent: 75.0 },
  { name: 'BAJAJ ELECT.LTD', symbol: 'BAJAJELEC', percent: 60.0 },
  { name: 'LTIMINDTREE LIMITED', symbol: 'LTIM', percent: 70.0 },
  { name: 'HERO MOTOCORP LIMITED', symbol: 'HEROMOTOCO', percent: 75.0 },
  { name: 'IFB INDUSTRIES LTD', symbol: 'IFBIND', percent: 60.0 },
  { name: 'EMAMI LIMITED', symbol: 'EMAMILTD', percent: 60.0 },
  { name: 'PRAJ INDUSTRIES LTD', symbol: 'PRAJIND', percent: 60.0 },
  { name: 'ALKEM LABORATORIES LTD.', symbol: 'ALKEM', percent: 75.0 },
  { name: 'BAJAJ FINSERV LTD.', symbol: 'BAJAJFINSV', percent: 70.0 },
  { name: 'INDRAPRASTHA GAS LTD', symbol: 'IGL', percent: 70.0 },
  { name: 'L\u0026T TECHNOLOGY SER. LTD.', symbol: 'LTTS', percent: 70.0 },
  { name: 'RATEGAIN TRAVEL TECHN LTD', symbol: 'RATEGAIN', percent: 60.0 },
  { name: 'GAIL (INDIA) LTD', symbol: 'GAIL', percent: 75.0 },
  { name: 'PCBL LIMITED', symbol: 'PCBL', percent: 60.0 },
  { name: 'ALKYL AMINES CHEM. LTD', symbol: 'ALKYLAMINE', percent: 60.0 },
  { name: 'HINDALCO  INDUSTRIES  LTD', symbol: 'HINDALCO', percent: 70.0 },
  {
    name: 'BAJAJ HOLDINGS \u0026 INVS LTD',
    symbol: 'BAJAJHLDNG',
    percent: 60.0,
  },
  { name: 'HCL TECHNOLOGIES LTD', symbol: 'HCLTECH', percent: 75.0 },
  { name: 'RATNAMANI MET \u0026 TUB LTD.', symbol: 'RATNAMANI', percent: 60.0 },
  { name: 'THE INDIAN HOTELS CO. LTD', symbol: 'INDHOTEL', percent: 70.0 },
  { name: 'LUPIN LIMITED', symbol: 'LUPIN', percent: 75.0 },
  { name: 'GALAXY SURFACTANTS LTD', symbol: 'GALAXYSURF', percent: 65.0 },
  { name: 'PIRAMAL ENTERPRISES LTD', symbol: 'PEL', percent: 65.0 },
  { name: 'BAJAJ FINANCE LIMITED', symbol: 'BAJFINANCE', percent: 70.0 },
  { name: 'THE INDIA CEMENTS LIMITED', symbol: 'INDIACEM', percent: 65.0 },
  { name: 'LUX INDUSTRIES LIMITED', symbol: 'LUXIND', percent: 60.0 },
  { name: 'HDFC AMC LIMITED', symbol: 'HDFCAMC', percent: 75.0 },
  { name: 'KOTAK MAHINDRA BANK LTD', symbol: 'KOTAKBANK', percent: 75.0 },
  { name: 'RESTAURANT BRAND ASIA LTD', symbol: 'RBA', percent: 60.0 },
  { name: 'HINDUSTAN COPPER LTD', symbol: 'HINDCOPPER', percent: 60.0 },
  { name: 'PERSISTENT SYSTEMS LTD', symbol: 'PERSISTENT', percent: 70.0 },
  { name: 'AMARA RAJA BATTERIES LTD.', symbol: 'AMARAJABAT', percent: 70.0 },
  { name: 'LAXMI ORGANIC INDUS LTD', symbol: 'LXCHEM', percent: 60.0 },
  { name: 'HDFC BANK LTD', symbol: 'HDFCBANK', percent: 75.0 },
  { name: 'PETRONET LNG LIMITED', symbol: 'PETRONET', percent: 75.0 },
  { name: 'INDIAMART INTERMESH LTD', symbol: 'INDIAMART', percent: 70.0 },
  { name: 'KPIT TECHNOLOGIES LIMITED', symbol: 'KPITTECH', percent: 60.0 },
  { name: 'HINDUSTAN PETROLEUM CORP', symbol: 'HINDPETRO', percent: 70.0 },
  { name: 'BALKRISHNA IND. LTD', symbol: 'BALKRISIND', percent: 75.0 },
  { name: 'POWER FIN CORP LTD.', symbol: 'PFC', percent: 75.0 },
  { name: 'AMBER ENTERPRISES (I) LTD', symbol: 'AMBER', percent: 60.0 },
  { name: 'RASHTRIYA CHEMICALS \u0026 FER', symbol: 'RCF', percent: 60.0 },
  { name: 'KPR MILL LTD.', symbol: 'KPRMILL', percent: 60.0 },
  { name: 'KAJARIA CERAMICS LTD', symbol: 'KAJARIACER', percent: 60.0 },
  { name: 'INDIAN BANK', symbol: 'INDIANB', percent: 60.0 },
  { name: 'HINDUSTAN UNILEVER LTD.', symbol: 'HINDUNILVR', percent: 75.0 },
  { name: 'PFIZER LTD', symbol: 'PFIZER', percent: 60.0 },
  { name: 'AMRUTAJAN HEALTH LTD', symbol: 'AMRUTANJAN', percent: 60.0 },
  { name: 'KANSAI NEROLAC PAINTS LTD', symbol: 'KANSAINER', percent: 65.0 },
  { name: 'AMI ORGANICS LIMITED', symbol: 'AMIORG', percent: 60.0 },
  { name: 'AEGIS LOGISTICS LIMITED', symbol: 'AEGISCHEM', percent: 60.0 },
  { name: 'REDINGTON LIMITED', symbol: 'REDINGTON', percent: 60.0 },
  { name: 'HOME FIRST FIN CO IND LTD', symbol: 'HOMEFIRST', percent: 60.0 },
  { name: '3M INDIA LIMITED', symbol: '3MINDIA', percent: 60.0 },
  { name: 'HEMISPHERE PROP IND LTD', symbol: 'HEMIPROP', percent: 60.0 },
  { name: 'THE PHOENIX MILLS LTD', symbol: 'PHOENIXLTD', percent: 60.0 },
  { name: 'AFFLE (INDIA) LIMITED', symbol: 'AFFLE', percent: 60.0 },
  { name: 'BANDHAN BANK LIMITED', symbol: 'BANDHANBNK', percent: 65.0 },
  { name: 'RELAXO FOOT LTD.', symbol: 'RELAXO', percent: 65.0 },
  { name: 'KEI INDUSTRIES LTD.', symbol: 'KEI', percent: 60.0 },
  { name: 'ANGEL ONE LIMITED', symbol: 'ANGELONE', percent: 60.0 },
  { name: 'PIDILITE INDUSTRIES LTD', symbol: 'PIDILITIND', percent: 75.0 },
  { name: 'RELIANCE INDUSTRIES LTD', symbol: 'RELIANCE', percent: 75.0 },
  { name: 'AARTI INDUSTRIES LTD', symbol: 'AARTIIND', percent: 70.0 },
  { name: 'KRISHNA INST OF MED SCI L', symbol: 'KIMS', percent: 60.0 },
  { name: 'BANK OF BARODA', symbol: 'BANKBARODA', percent: 70.0 },
  { name: 'PI INDUSTRIES LTD', symbol: 'PIIND', percent: 75.0 },
  { name: 'ANUPAM RASAYAN INDIA LTD', symbol: 'ANURAS', percent: 60.0 },
  { name: 'AAVAS FINANCIERS LIMITED', symbol: 'AAVAS', percent: 60.0 },
  { name: 'NIP IND ETF BANK BEES', symbol: 'BANKBEES', percent: 70.0 },
  { name: 'PUNJAB NATIONAL BANK', symbol: 'PNB', percent: 65.0 },
  { name: 'APAR INDUSTRIES LTD.', symbol: 'APARINDS', percent: 60.0 },
  { name: 'ABB INDIA LIMITED', symbol: 'ABB', percent: 75.0 },
  { name: 'RITES LIMITED', symbol: 'RITES', percent: 65.0 },
  { name: 'BANK OF INDIA', symbol: 'BANKINDIA', percent: 60.0 },
  { name: 'APL APOLLO TUBES LTD', symbol: 'APLAPOLLO', percent: 60.0 },
  { name: 'ABBOTT INDIA LIMITED', symbol: 'ABBOTINDIA', percent: 70.0 },
  { name: 'ALEMBIC PHARMA LTD', symbol: 'APLLTD', percent: 60.0 },
  { name: 'ADITYA BIRLA CAPITAL LTD.', symbol: 'ABCAPITAL', percent: 70.0 },
  { name: 'BARBEQUE NATION HOSP. LTD', symbol: 'BARBEQUE', percent: 60.0 },
  { name: 'ADITYA BIRLA FASHION \u0026 RT', symbol: 'ABFRL', percent: 65.0 },
  { name: 'BASF INDIA LTD', symbol: 'BASF', percent: 60.0 },
  { name: 'ADIT BIRL SUN LIF AMC LTD', symbol: 'ABSLAMC', percent: 60.0 },
  { name: 'BATA INDIA LTD', symbol: 'BATAINDIA', percent: 75.0 },
  { name: 'BAYER CROPSCIENCE LTD', symbol: 'BAYERCROP', percent: 60.0 },
];
